### ISSUE TITLE
Static mapping of several DGId's with a YSF Clients - very similar like the handling of the YCS Server's

### ISSUE THREAD

**Issue by DC9VQ** [iu5jae/pYSFReflector3#1]
Hi David, hi Antonio,

many thanks for this great multistream reflector. I sucessfully installed the reflector and it works. I setup a bridge from a pYSF Reflector to my pYSF3 using your great software ysf_bridge.

setup of my pYSF3:
Default DGId = 50
Bridge to YSF00169 on DGId= 51

Now my question. Am I able to statical map the DgId's 50, 51 in the YSF Client and when a QSO starts on 50 or 51 I can RX it ? The YCS Servers are able to do that with an Option String like "Options=50,51".

With this feature we could setup an pYSF3 for Germany as a kind of aggregator for single YSF Reflectors.

73,
Michael (DC9VQ)

![Bildschirmfoto 2023-11-26 um 12 54 44](https://github.com/iu5jae/pYSFReflector3/assets/68436803/1eb5eb09-4b3a-444e-b08f-f3c86db9182d)

**Comment by iu5jae** [comment]
Currently you can only listen to one DG-ID at time, with the Options string you can set the "back to home" (BTH) on a DG-ID with the time set on the reflector.

**Comment by DC9VQ** [comment]
Thanks for your reply and for the hint. Maybe it's possible in the future. Again, many thanks for your great software that you share with us !!
