### ISSUE TITLE
sporadic database locks which prevent the refresh of the dashboard data

### ISSUE THREAD

**Issue by DC9VQ** [iu5jae/pYSFReflector3#2]
Hi Antonio,

we installed the pYSF3 reflector and started using it in Germany. We have 1-2 times a day an issue with the dashboard. It seems that there occur database locks which prevent the refresh of the dashboard data (main.php).

Do you know this issue ? Any hints to prevent that ?

73,
Michael 

2023] [proxy_fcgi:error] [pid 3685:tid 140478372603584] [client 93.206.59.198:60150] AH01071: Got error 'PHP message: PHP Warning:  SQLite3::query(): Unable to prepare statement: 5, database is locked in /var/www/html/main.php on line 90; PHP message: PHP Fatal error:  Uncaught Error: Call to a member function fetchArray() on bool in /var/www/html/main.php:92\nStack trace:\n#0 {main}\n  thrown in /var/www/html/main.php on line 92', referer: https://ysf-deutschland.de/main.php

**Comment by DC9VQ** [comment]
Hi Antonio, 
it seems that the database is not the issue for the stop/crash of the collector3.py. In very rare cases we identified some additional characters from the bridges (we are using mainly ysf_bridge) that we run. If those characters will be send in the "to ALL" field the collector crash.

M: 2024-02-08 19:49:27.404 <1391794> Received data from DO0HM      to ALL<0><0><0><0><0><0><0>  at YSF07588   FICH-Data: CS:2 | CM:0 | FT:7 | Dev:False | MR:2 | VoIP:False | DT:2 | SQL:False | SQC:72

Any idea how to fix that ?

73,
Michael (DC9VQ)

**Comment by iu5jae** [comment]
Check if the problem has been resolved with the latest version.

Antonio
IU5JAE

**Comment by DC9VQ** [comment]
Hi Antonio,

it seems that the bug is fixed. Many thanks.

73,
Michael - DC9VQ
